'use client';
import {useEffect,useState,useRef} from 'react';
import {CalendarDays,Check,ChevronLeft,ChevronRight,Utensils,Leaf,UserRound,LogOut,ClipboardList,ChefHat,Clock,Download,Plus,X,Smartphone,Info,LoaderCircle,CheckCircle2} from 'lucide-react';
import {students,weekDates,deadline,type Choice,type Menu} from './domain';
type Row={student:string;date:string;choice:Choice};
type View='menu'|'choices'|'kitchen';
type WeekData={week:number;menus:Menu[];choices:Row[]};
const days=['Segunda','Terça','Quarta','Quinta','Sexta'];
const labels={normal:'Prato do dia',vegetarian:'Vegetariano',none:'Não vou almoçar'};
const fmt=(date:string,options:Intl.DateTimeFormatOptions={day:'numeric',month:'short'})=>new Intl.DateTimeFormat('pt-PT',{...options,timeZone:'UTC'}).format(new Date(date+'T12:00:00Z'));
export default function Cantina(){
 const [view,setView]=useState<View>('menu'),[week,setWeek]=useState(0),[day,setDay]=useState(0);
 const [student,setStudent]=useState(students[0]),[data,setData]=useState<WeekData|null>(null),[draft,setDraft]=useState<Record<string,Choice>>({});
 const [loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[loadError,setLoadError]=useState(''),[toast,setToast]=useState(''),[needsSignIn,setNeedsSignIn]=useState(false);
 const [account,setAccount]=useState(false),[install,setInstall]=useState(false),[editor,setEditor]=useState<Menu|null>(null),[installPrompt,setInstallPrompt]=useState<any>(null);
 const [studentNumber,setStudentNumber]=useState(''),[loginError,setLoginError]=useState('');
 const modalRef=useRef<HTMLDialogElement>(null),activeRequest=useRef(0);
 // Only a successfully loaded snapshot for the selected week can enable actions.
 const ready=!loading&&data?.week===week;
 const unavailable=loading?'A carregar…':'Dados indisponíveis';
 const menus=data?.week===week?data.menus:weekDates(week).map(date=>({date,normal:'Ementa indisponível',vegetarian:'Ementa indisponível',soup:'Ementa indisponível',dessert:'Ementa indisponível'}));
 const rows=ready?data.choices:[];
 const load=async(w:number)=>{
  const request=++activeRequest.current;setLoading(true);setLoadError('');setData(null);
  try{const r=await fetch('/api/demo?week='+w);const data=await r.json() as {error?:string;menus:Menu[];choices:Row[]};if(request!==activeRequest.current)return;
   if(!r.ok){setNeedsSignIn(r.status===401);throw Error(data.error ?? 'Ocorreu um erro.');}setData({week:w,menus:data.menus,choices:data.choices});setNeedsSignIn(false);
  }catch(e){if(request===activeRequest.current)setLoadError(e instanceof Error?e.message:'Não foi possível carregar.');}
  finally{if(request===activeRequest.current)setLoading(false);}
 };
 useEffect(()=>{setDraft({});setDay(0);setEditor(null);setError('');void load(week);return()=>{activeRequest.current++;};},[week]);
 useEffect(()=>{const register=()=>navigator.serviceWorker?.register('/sw.js').catch(()=>{});register();const fn=(e:Event)=>{e.preventDefault();setInstallPrompt(e);};window.addEventListener('beforeinstallprompt',fn);return()=>window.removeEventListener('beforeinstallprompt',fn);},[]);
 useEffect(()=>{if(toast){const t=setTimeout(()=>setToast(''),4500);return()=>clearTimeout(t);}},[toast]);
 useEffect(()=>{if(account||install||editor)modalRef.current?.showModal();else modalRef.current?.close();},[account,install,editor]);
 useEffect(()=>{if(account){setStudentNumber('');setLoginError('');}},[account]);
 const chosen=(date:string)=>draft[date]??rows.find(r=>r.student===student.id&&r.date===date)?.choice;
 const count=(date:string,c:Choice)=>rows.filter(r=>r.date===date&&r.choice===c).length;
 const confirmed=menus.filter(m=>rows.some(r=>r.student===student.id&&r.date===m.date)).length;
 const meals=menus.filter(m=>{const c=chosen(m.date);return c==='normal'||c==='vegetarian';}).length;
 const pending=Object.keys(draft).length;
 const close=()=>{setAccount(false);setInstall(false);setEditor(null);};
 const login=(e:React.FormEvent)=>{e.preventDefault();if(busy||pending>0)return;const profile=students.find(s=>s.number===studentNumber.trim());if(!profile){setLoginError('Nesta demonstração, usa o número 1001, 1002 ou 1003. O acesso aos números reais será ligado à API da escola.');return;}setStudent(profile);setDraft({});close();};
 const choose=(date:string,c:Choice)=>{if(!ready||busy||new Date()>deadline(date))return;setDraft(d=>({...d,[date]:c}));setError('');};
 const save=async()=>{if(!pending||busy||!ready)return;setBusy(true);setError('');try{
  const r=await fetch('/api/demo',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type:'choices',student:student.id,items:Object.entries(draft).map(([date,choice])=>({date,choice}))})});const data=await r.json() as {error?:string;menus:Menu[];choices:Row[]};if(!r.ok)throw Error(data.error ?? 'Ocorreu um erro.');
  setData(prev=>prev&&({...prev,choices:[...prev.choices.filter(r=>!(r.student===student.id&&Object.hasOwn(draft,r.date))),...Object.entries(draft).map(([date,choice])=>({student:student.id,date,choice}))]}));setDraft({});setToast('Escolhas confirmadas. A cantina já tem as quantidades.');
 }catch(e){setError(e instanceof Error?e.message:'Não foi possível confirmar.');}finally{setBusy(false);}};
 const saveMenu=async(e:React.FormEvent)=>{e.preventDefault();if(!editor||busy||!ready)return;setBusy(true);setError('');try{const r=await fetch('/api/demo',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type:'menu',menu:editor})});const data=await r.json() as {error?:string;menus:Menu[];choices:Row[]};if(!r.ok)throw Error(data.error ?? 'Ocorreu um erro.');setData(prev=>prev&&({...prev,menus:prev.menus.map(m=>m.date===editor.date?editor:m)}));setEditor(null);setToast('Ementa atualizada.');}catch(e){setError(e instanceof Error?e.message:'Não foi possível guardar.');}finally{setBusy(false);}};
 const go=(v:View)=>{setView(v);setError('');};
 const csv=()=>{if(!ready||busy)return;const text='\uFEFFData;Prato do dia;Vegetariano;Não almoça;Sem resposta;Total a preparar\r\n'+menus.map(m=>[m.date,count(m.date,'normal'),count(m.date,'vegetarian'),count(m.date,'none'),students.length-rows.filter(r=>r.date===m.date).length,count(m.date,'normal')+count(m.date,'vegetarian')].join(';')).join('\r\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'text/csv;charset=utf-8;'}));a.download='cantina-'+menus[0].date+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);};
 const current=menus[day];
 return <div className="app-shell">
  <a className="skip-link" href="#main">Saltar para o conteúdo</a>
  <aside className="sidebar">
   <a className="brand" href="/" aria-label="EPT Cantina"><span className="brand-letters">ept<span>.</span></span><span className="brand-caption">ESCOLA PROFISSIONAL<br/>DE TRANCOSO</span></a>
   <div className="brand-spectrum" aria-hidden="true"><i/><i/><i/><i/></div>
   <div className="side-section">A TUA CANTINA</div>
   <nav aria-label="Navegação principal"><button className={view==='menu'?'nav-item active':'nav-item'} onClick={()=>go('menu')}><CalendarDays size={20}/>Ementa semanal</button><button className={view==='choices'?'nav-item active':'nav-item'} onClick={()=>go('choices')}><ClipboardList size={20}/>Minhas escolhas<span className="nav-counter">{ready?confirmed:'—'}</span></button><button className={view==='kitchen'?'nav-item active':'nav-item'} onClick={()=>go('kitchen')}><ChefHat size={20}/>Painel da cantina</button></nav>
   <div className="sidebar-bottom"><button className="install-link" onClick={()=>setInstall(true)}><Smartphone size={19}/>Adicionar ao telemóvel<Plus size={16}/></button><div className="school-caption">EPT · Cantina escolar<br/><span>Ano letivo 2026 / 2027</span></div></div>
  </aside>
  <div className="main-shell"><header className="topbar"><span className="mobile-brand">ept<span>.</span></span><div className="breadcrumbs">Cantina<span>/</span>{view==='menu'?'Ementa semanal':view==='choices'?'Minhas escolhas':'Gestão de refeições'}</div><button className="profile-button" onClick={()=>setAccount(true)}><span className="avatar">{student.name[0]}</span><span className="profile-text">{student.name}<small>Aluno n.º {student.number}</small></span><ChevronRight size={15}/></button></header>
   <main id="main"><div className="demo-notice"><Info size={16}/><span>Demonstração · Ementas e perfis fictícios. Login da escola ainda não ligado.</span><button onClick={()=>setAccount(true)}>Trocar perfil</button></div>
    <div className="page-heading"><div><p className="eyebrow">{view==='kitchen'?'PLANEAMENTO DA CANTINA':'ALMOÇO NA ESCOLA'}</p><h1>{view==='menu'?'Ementa da semana':view==='choices'?'As tuas escolhas':'Cada refeição conta.'}</h1><p>{view==='kitchen'?'Quantidades confirmadas para preparar cada dia.':'Escolhe o teu almoço. Ajuda a cantina a preparar a quantidade certa.'}</p></div><span className="open-label"><Clock size={15}/>Marcações abertas</span></div>
    <div className="week-bar"><div className="week-label"><CalendarDays size={20}/><strong>{fmt(menus[0].date,{day:'numeric'})} – {fmt(menus[4].date,{day:'numeric',month:'long'})}</strong><span>{week===0?'Próxima semana':'Semana seguinte'}</span></div><div className="week-controls"><button aria-label="Semana anterior" disabled={week===0||busy||pending>0} onClick={()=>setWeek(w=>w-1)}><ChevronLeft size={19}/></button><button aria-label="Semana seguinte" disabled={week===3||busy||pending>0} onClick={()=>setWeek(w=>w+1)}><ChevronRight size={19}/></button></div></div>
    {!ready&&<p className="week-data-status" role="status">{loading?'A carregar os dados desta semana…':'Dados desta semana indisponíveis. Tenta carregar novamente.'}</p>}
    {loadError&&<div className="error-message" role="alert">{loadError}{needsSignIn?<a href="/signin-with-chatgpt?return_to=/" target="_top">Ativar demonstração</a>:<button disabled={busy||loading} onClick={()=>load(week)}>Tentar novamente</button>}</div>}
    {error&&!editor&&<div className="error-message" role="alert">{error}{needsSignIn?<a href="/signin-with-chatgpt?return_to=/" target="_top">Ativar demonstração</a>:<button disabled={busy||loading} onClick={()=>{setError('');void load(week);}}>Tentar novamente</button>}</div>}
    {view==='menu'&&<><div className="student-layout"><section className="menu-panel" aria-label="Escolher refeições"><div className="day-tabs" role="tablist" aria-label="Dias da semana">{menus.map((m,i)=><button key={m.date} role="tab" id={'day-'+i} aria-controls="daily-menu" aria-selected={day===i} onClick={()=>setDay(i)} className={day===i?'day-tab selected':'day-tab'}><span>{days[i]}</span><strong>{fmt(m.date,{day:'2-digit'})}</strong><small>{chosen(m.date)?<Check size={14}/>:<span className="empty-marker"/>}</small></button>)}</div>
     <div className="daily-menu" id="daily-menu" role="tabpanel" aria-labelledby={'day-'+day}><div className="daily-heading"><div><span className="eyebrow">{days[day].toUpperCase()} · ALMOÇO</span><h2>O que vai ser?</h2></div><span className="meal-time">12:00 – 14:00 <span>Horário de exemplo</span></span></div><div className="meal-options">{(['normal','vegetarian'] as const).map(c=><button key={c} aria-pressed={chosen(current.date)===c} className={'meal-option '+c+(chosen(current.date)===c?' picked':'')} disabled={!ready||busy||new Date()>deadline(current.date)} onClick={()=>choose(current.date,c)}><div className="option-top"><span className="meal-icon">{c==='normal'?<Utensils size={25}/>:<Leaf size={25}/>}</span><span className="radio-circle">{chosen(current.date)===c&&<Check size={14}/>}</span></div><span className="option-type">{labels[c]}</span><h3>{current[c]}</h3><span className="option-action">{chosen(current.date)===c?'Selecionado':'Selecionar refeição'}</span></button>)}</div><div className="meal-extras"><div><span>PARA COMEÇAR</span><p>{current.soup}</p></div><div><span>PARA TERMINAR</span><p>{current.dessert}</p></div></div><button aria-pressed={chosen(current.date)==='none'} className={'no-meal '+(chosen(current.date)==='none'?'picked':'')} disabled={!ready||busy||new Date()>deadline(current.date)} onClick={()=>choose(current.date,'none')}><span className="radio-circle">{chosen(current.date)==='none'&&<Check size={14}/>}</span>Não vou almoçar neste dia</button></div>
    </section><aside className="week-summary"><div className="summary-heading"><ClipboardList size={19}/><h2>A tua semana</h2><span>{ready?`${meals}/5`:'—'}</span></div><p className="summary-intro">As escolhas só ficam marcadas depois de confirmares.</p><div className="summary-days">{menus.map((m,i)=><button key={m.date} onClick={()=>setDay(i)} className={day===i?'summary-day focused':'summary-day'}><span className="summary-date"><strong>{days[i].slice(0,3)}</strong><small>{fmt(m.date,{day:'2-digit'})}</small></span><span className={'summary-choice '+(chosen(m.date)||'unset')}>{chosen(m.date)?labels[chosen(m.date)!]:ready?'Por escolher':unavailable}{draft[m.date]&&<small>Por confirmar</small>}</span>{chosen(m.date)&&!draft[m.date]&&<CheckCircle2 size={16}/>}</button>)}</div><button className="primary-button confirm-button" disabled={!pending||busy||!ready} onClick={save}>{busy?<LoaderCircle className="spin" size={17}/>:<Check size={17}/>} {busy?'A confirmar…':pending?'Confirmar escolhas':confirmed===5?'Escolhas confirmadas':'Confirmar escolhas'}</button><p className="summary-footnote">{pending?`${pending} ${pending===1?'escolha por confirmar':'escolhas por confirmar'}`:!ready?unavailable:confirmed?`${confirmed} de 5 dias confirmados`:'Ainda não confirmaste nenhuma escolha'}</p></aside></div><div className="deadline-note"><Clock size={19}/><div><strong>Planeia com antecedência</strong><p>Prazo de exemplo: até às 18h UTC do dia útil anterior. Pode ser ajustado pela escola.</p></div></div></>}
    {view==='choices'&&<section className="choices-section"><div className="section-heading"><h2>Resumo semanal</h2><span>{ready?`${confirmed} de 5 dias confirmados`:unavailable}</span></div>{menus.map((m,i)=><div className="choice-row" key={m.date}><div className="choice-day"><strong>{days[i]}</strong><span>{fmt(m.date)}</span></div><div className="choice-meal"><strong>{chosen(m.date)?labels[chosen(m.date)!]:ready?'Ainda sem escolha':unavailable}</strong><p>{chosen(m.date)==='normal'?m.normal:chosen(m.date)==='vegetarian'?m.vegetarian:chosen(m.date)==='none'?'Não está prevista uma refeição.':ready?'Escolhe uma refeição na ementa semanal.':'Aguarda o carregamento dos dados desta semana.'}</p></div><span className={'status-badge '+(draft[m.date]?'draft':'')}>{draft[m.date]?'Por confirmar':chosen(m.date)?'Confirmado':ready?'Pendente':unavailable}</span><button className="text-button" disabled={!ready||busy} onClick={()=>{setDay(i);setView('menu');}}>Alterar</button></div>)}</section>}
    {view==='kitchen'&&<><div className="kitchen-stats"><div><span>REFEIÇÕES A PREPARAR</span><strong>{ready?rows.filter(r=>r.choice!=='none').length:'—'}</strong><p>Soma dos cinco dias</p></div><div><span>PRATO DO DIA</span><strong>{ready?rows.filter(r=>r.choice==='normal').length:'—'}</strong><p>Marcações confirmadas</p></div><div><span>VEGETARIANO</span><strong>{ready?rows.filter(r=>r.choice==='vegetarian').length:'—'}</strong><p>Marcações confirmadas</p></div><div><span>RESPOSTAS EM FALTA</span><strong>{ready?students.length*menus.length-rows.length:'—'}</strong><p>3 perfis × 5 dias</p></div></div><section className="kitchen-section"><div className="section-heading"><div><h2>Preparação por dia</h2><p>Contagens dos três perfis de demonstração.</p></div><button className="secondary-button" onClick={csv} disabled={!ready||busy}><Download size={16}/>Exportar CSV</button></div><div className="table-scroll"><table><thead><tr><th>Dia</th><th>Prato do dia</th><th>Vegetariano</th><th>Não almoça</th><th>Sem resposta</th><th>A preparar</th><th><span className="sr-only">Ações</span></th></tr></thead><tbody>{menus.map((m,i)=><tr key={m.date}><td><strong>{days[i]}</strong><span>{fmt(m.date)}</span></td><td>{ready?count(m.date,'normal'):'—'}</td><td>{ready?count(m.date,'vegetarian'):'—'}</td><td>{ready?count(m.date,'none'):'—'}</td><td>{ready?students.length-rows.filter(r=>r.date===m.date).length:'—'}</td><td><strong className="total-badge">{ready?count(m.date,'normal')+count(m.date,'vegetarian'):'—'}</strong></td><td><button className="text-button" onClick={()=>setEditor({...m})} disabled={!ready||busy}>Editar ementa</button></td></tr>)}</tbody></table></div></section><p className="kitchen-note"><Info size={16}/>Nesta demonstração podes testar os dois papéis. Os acessos reais serão definidos com a escola.</p></>}
    <footer className="page-footer"><span>EPT · Escola Profissional de Trancoso</span><span>Ementa de demonstração</span></footer>
   </main><nav className="mobile-nav" aria-label="Navegação móvel"><button className={view==='menu'?'active':''} onClick={()=>go('menu')}><CalendarDays size={20}/><span>Ementa</span></button><button className={view==='choices'?'active':''} onClick={()=>go('choices')}><ClipboardList size={20}/><span>Escolhas</span></button><button className={view==='kitchen'?'active':''} onClick={()=>go('kitchen')}><ChefHat size={20}/><span>Cantina</span></button></nav>
  </div>
  <dialog ref={modalRef} className="app-dialog" onCancel={close}><button className="dialog-close" aria-label="Fechar" onClick={close}><X size={20}/></button>
   {account&&<form onSubmit={login}><span className="dialog-icon"><UserRound size={25}/></span><p className="eyebrow">ACESSO À CANTINA</p><h2>Entrar na EPT</h2><p className="dialog-description">Escreve o teu número de aluno para entrar. O acesso real será ligado à API da escola.</p><label className="field-label">Número de aluno<input type="text" name="username" inputMode="numeric" autoComplete="username" placeholder="Escreve o teu número de aluno" required pattern="[0-9]{1,12}" title="Escreve apenas números" maxLength={12} value={studentNumber} disabled={busy||pending>0} aria-invalid={!!loginError} aria-describedby={loginError?'login-error':'demo-numbers'} onChange={e=>{setStudentNumber(e.target.value);setLoginError('');}}/></label><p id="demo-numbers" className="dialog-hint">Para testar: 1001, 1002 ou 1003.</p><label className="field-label">Palavra-passe · NIF<input type="password" placeholder="Disponível após ligar a API da escola" disabled autoComplete="off"/></label>{loginError&&<p id="login-error" className="error-message" role="alert">{loginError}</p>}{pending>0&&<p className="dialog-hint">Confirma as escolhas pendentes antes de trocar de perfil.</p>}<button type="submit" className="primary-button" disabled={busy||pending>0||!studentNumber.trim()}><Check size={17}/>Continuar em demonstração</button><p className="dialog-hint">Não introduzas dados pessoais nesta versão.</p></form>}
   {install&&<><span className="dialog-icon"><Smartphone size={26}/></span><p className="eyebrow">SEMPRE À MÃO</p><h2>A cantina no teu telemóvel</h2><p className="dialog-description">Adiciona a app ao ecrã principal para abrires diretamente.</p><div className="install-step"><strong>iPhone · Safari</strong><p>Toca em Partilhar, depois em “Adicionar ao ecrã principal”.</p></div><div className="install-step"><strong>Android · Chrome</strong><p>Abre o menu ⋮ e escolhe “Adicionar ao ecrã principal” ou “Instalar aplicação”.</p></div>{installPrompt&&<button className="primary-button" onClick={async()=>{await installPrompt.prompt();setInstallPrompt(null);}}>Instalar aplicação</button>}<p className="dialog-hint">É necessária ligação à internet para consultar e confirmar refeições.</p></>}
   {editor&&<form onSubmit={saveMenu}><p className="eyebrow">PAINEL DA CANTINA</p><h2>Editar ementa</h2><p className="dialog-description">{fmt(editor.date,{weekday:'long',day:'numeric',month:'long'})}</p>{(['normal','vegetarian','soup','dessert'] as const).map(k=><label key={k} className="field-label">{k==='soup'?'Sopa':k==='dessert'?'Sobremesa':labels[k]}<input required maxLength={160} value={editor[k]} onChange={e=>setEditor({...editor,[k]:e.target.value})}/></label>)}{error&&<p className="error-message" role="alert">{error}</p>}<button className="primary-button" disabled={busy||!ready}>{busy?'A guardar…':'Guardar ementa'}</button></form>}
  </dialog>{toast&&<div className="toast" role="status"><CheckCircle2 size={20}/>{toast}</div>}
 </div>;
}

